/*
 * This file was automatically generated by EvoSuite
 * Thu Feb 12 02:02:32 GMT 2026
 */

package br.com.exemplo;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.com.exemplo.Calculadora;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Calculadora_ESTest extends Calculadora_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      boolean boolean0 = calculadora0.ehPar((-2694));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      boolean boolean0 = calculadora0.ehPar((-4311));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      double double0 = calculadora0.calcularDesconto(2);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      double double0 = calculadora0.calcularDesconto(616.6794156462);
      assertEquals(30.833970782310004, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      // Undeclared exception!
      try { 
        calculadora0.calcularDesconto((-1.0));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Valor inv\u00C3\u00A1lido
         //
         verifyException("br.com.exemplo.Calculadora", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Calculadora calculadora0 = new Calculadora();
      double double0 = calculadora0.calcularDesconto(1897.0426148696329);
      assertEquals(189.7042614869633, double0, 0.01);
  }
}
